import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, subject, message } = body;

    // Validate the input
    if (!name || !email || !message) {
      return NextResponse.json(
        { error: "Name, email, and message are required" },
        { status: 400 }
      );
    }

    // Email to Portfolio Owner
    const { data, error } = await resend.emails.send({
      from: "Portfolio <onboarding@resend.dev>", // Once you add a domain, change this to "Portfolio <hello@yourdomain.com>"
      to: process.env.CONTACT_EMAIL || "muhammadtayyab3753@gmail.com",
      replyTo: email,
      subject: `New Lead: ${subject || "Portfolio Contact"}`,
      html: `
        <!DOCTYPE html>
        <html>
        <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f5; margin: 0; padding: 40px 0;">
          <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); overflow: hidden;">
            <tr>
              <td style="background-color: #2563eb; padding: 30px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">New Message from Portfolio</h1>
              </td>
            </tr>
            <tr>
              <td style="padding: 40px 30px;">
                <p style="color: #4b5563; font-size: 16px; margin-bottom: 24px;">You have received a new message from your portfolio website's contact form.</p>
                
                <table border="0" cellpadding="10" cellspacing="0" width="100%" style="background-color: #f8fafc; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 24px;">
                  <tr>
                    <td width="100" style="color: #64748b; font-weight: 600; font-size: 14px; border-bottom: 1px solid #e2e8f0;">Name:</td>
                    <td style="color: #0f172a; font-size: 15px; font-weight: 500; border-bottom: 1px solid #e2e8f0;">${name}</td>
                  </tr>
                  <tr>
                    <td style="color: #64748b; font-weight: 600; font-size: 14px; border-bottom: 1px solid #e2e8f0;">Email:</td>
                    <td style="color: #0f172a; font-size: 15px; font-weight: 500; border-bottom: 1px solid #e2e8f0;"><a href="mailto:${email}" style="color: #2563eb; text-decoration: none;">${email}</a></td>
                  </tr>
                  <tr>
                    <td style="color: #64748b; font-weight: 600; font-size: 14px;">Subject:</td>
                    <td style="color: #0f172a; font-size: 15px; font-weight: 500;">${subject || "N/A"}</td>
                  </tr>
                </table>

                <h3 style="color: #0f172a; font-size: 16px; margin-bottom: 10px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Message Content</h3>
                <div style="color: #334155; font-size: 15px; line-height: 1.6; background-color: #ffffff; padding: 15px; border: 1px solid #e2e8f0; border-left: 4px solid #2563eb; border-radius: 4px; white-space: pre-wrap;">${message}</div>
              </td>
            </tr>
            <tr>
              <td style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
                <p style="color: #94a3b8; font-size: 13px; margin: 0;">This email was automatically generated by your portfolio website.</p>
              </td>
            </tr>
          </table>
        </body>
        </html>
      `,
    });

    if (error) {
      console.error("Resend error (Owner):", error);
      return NextResponse.json(
        { error: "Failed to send message. Please try again or email directly." },
        { status: 500 }
      );
    }

    // Auto-reply (sending to the client's email)
    // Wrapped in try/catch so if domain is unverified on Resend, it fails silently for the user
    try {
      await resend.emails.send({
        from: "Muhammad Tayyab <onboarding@resend.dev>", // Requires verified domain to send to arbitrary emails
        to: email,
        subject: `Thank you for reaching out, ${name}!`,
        html: `
          <!DOCTYPE html>
          <html>
          <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f5; margin: 0; padding: 40px 0;">
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); overflow: hidden;">
              <tr>
                <td style="background-color: #0f172a; padding: 40px 30px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 26px; font-weight: 600; letter-spacing: 0.5px;">Hello, ${name}!</h1>
                </td>
              </tr>
              <tr>
                <td style="padding: 40px 30px;">
                  <p style="color: #334155; font-size: 16px; line-height: 1.6; margin-bottom: 20px;">
                    Thank you for reaching out to me through my portfolio website. This is to confirm that I have successfully received your message regarding <strong>"${subject || "your inquiry"}"</strong>.
                  </p>
                  <p style="color: #334155; font-size: 16px; line-height: 1.6; margin-bottom: 30px;">
                    I appreciate your interest and will review your message shortly. I aim to respond to all inquiries within 24-48 hours. I look forward to connecting with you soon!
                  </p>
                  
                  <div style="border-top: 1px solid #e2e8f0; padding-top: 30px; margin-top: 20px;">
                    <p style="color: #0f172a; font-size: 16px; font-weight: 600; margin: 0 0 5px 0;">Best Regards,</p>
                    <p style="color: #2563eb; font-size: 18px; font-weight: 700; margin: 0 0 5px 0;">Muhammad Tayyab</p>
                    <p style="color: #64748b; font-size: 14px; margin: 0;">Full Stack Developer | AI/ML Engineer</p>
                  </div>
                </td>
              </tr>
              <tr>
                <td style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
                  <p style="color: #94a3b8; font-size: 12px; margin: 0;">This is an automated response. Please do not reply directly to this email.</p>
                </td>
              </tr>
            </table>
          </body>
          </html>
        `,
      });
    } catch (clientEmailError) {
      console.error("Resend error (Client Auto-reply failed, likely due to unverified domain):", clientEmailError);
      // We don't return an error response here so the user still gets a "success" message on the frontend
    }

    return NextResponse.json(
      { message: "Message sent successfully! I'll get back to you soon." },
      { status: 200 }
    );
  } catch (error) {
    console.error("Contact form error:", error);
    return NextResponse.json(
      { error: "Failed to send message. Please try again or email directly." },
      { status: 500 }
    );
  }
}
